version: '3.8'

services:
  web:
    build:
      context: ./symmetrical_cart
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./symmetrical_cart/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    entrypoint: /usr/src/app/entrypoint.dev.sh
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      ./.env.db.dev

volumes:
  postgres_data:
