# Generated by Django 5.0 on 2023-12-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0012_product_release'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('ratings', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('delivery_location', models.CharField(blank=True, max_length=100, null=True)),
                ('current_orders', models.ManyToManyField(blank=True, related_name='current_delivery_user', to='shop.order')),
                ('delivered_orders', models.ManyToManyField(blank=True, related_name='delivered_delivery_user', to='shop.order')),
            ],
            options={
                'verbose_name': 'Delivery User',
                'verbose_name_plural': 'Delivery Users',
            },
        ),
    ]
