# Generated by Django 5.0 on 2023-12-24 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0012_product_release'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryUser',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('ratings', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('delivery_location', models.CharField(blank=True, max_length=100, null=True)),
                ('current_orders', models.ManyToManyField(blank=True, related_name='current_delivery_user', to='shop.order')),
                ('delivered_orders', models.ManyToManyField(blank=True, related_name='delivered_delivery_user', to='shop.order')),
            ],
            options={
                'verbose_name': 'Delivery User',
                'verbose_name_plural': 'Delivery Users',
            },
            bases=('shop.customuser',),
        ),
    ]
