# Generated by Django 5.0 on 2023-12-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receiver_name',
            field=models.CharField(default='name', max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_surname',
            field=models.CharField(default='surname', max_length=24),
            preserve_default=False,
        ),
    ]
