# Generated by Django 5.0 on 2023-12-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_order_delivered_order_delivered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_rate',
            field=models.IntegerField(default=1),
        ),
    ]
