# Generated by Django 5.0 on 2023-12-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_order_delivered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rated_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
