# Generated by Django 5.0 on 2023-12-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_order_rated_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
